src/Entity/Place.php
<?php

namespace App\Entity;

use App\Entity\User;
use DateTimeInterface;
use Cocur\Slugify\Slugify;
use App\Service\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlaceRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"slug"},
 *  message="Ce lieu est déjà enregistré... Un autre lieu existe avec le même nom et dans la même ville"
 * )
 */
class Place
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="place")
     */
    private $events;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="place")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity=District::class, inversedBy="place")
     */
    private $district;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=7, nullable=true)
     */
    private $latitude;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=7, nullable=true)
     */
    private $longitude;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $pronoun;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToOne(targetEntity=Placekind::class, inversedBy="placekindPrimary")
     */
    private $placekindPrimary;

    /**
     * @ORM\ManyToOne(targetEntity=Placekind::class, inversedBy="placekindSecondary")
     */
    private $placekindSecondary;

    /**
     * @ORM\ManyToOne(targetEntity=Placekind::class, inversedBy="placekindTertiary")
     */
    private $placekindTertiary;

    /**
     * @ORM\ManyToOne(targetEntity=Postcode::class, inversedBy="places")
     */
    private $postcode;

    /**
     * @ORM\ManyToMany(targetEntity=Placetag::class, mappedBy="places")
     */
    private $placetags;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $oldserial;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Oldurl;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $opening = [];

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $links = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mapUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $streetUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ip;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $transport = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $dataLink;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $opinion;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $wifi;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $lastService;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $parking;

    /**
     * @ORM\OneToMany(targetEntity=Claim::class, mappedBy="place")
     */
    private $claims;

    /**
     * @ORM\OneToMany(targetEntity=PlaceLike::class, mappedBy="place", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Room::class, mappedBy="place", orphanRemoval=true)
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=TicketResource::class, mappedBy="place")
     */
    private $resources;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $multiTitles = [];

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="placeEditors")
     */
    private $editors;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="placeAffirmers")
     */
    private $affirmers;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="placeAuthors")
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="place")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Reduction::class, mappedBy="places")
     */
    private $reductions;

    /**
     * @ORM\ManyToMany(targetEntity=Reduction::class, inversedBy="freePlaces")
     */
    private $freeReductions;

    //private $countOfEvents;


    public function __construct()
    {
        $this->events = new ArrayCollection();
        $this->placetags = new ArrayCollection();
        $this->claims = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->rooms = new ArrayCollection();
        $this->resources = new ArrayCollection();
        $this->editors = new ArrayCollection();
        $this->affirmers = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->reductions = new ArrayCollection();
        $this->freeReductions = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title.'-'.$this->city->getName());
        }
    }
    
    /**
     * Permet d'initialiser la date de création et de mise à jour
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
    */
    public function updatedTimestamps(): void
    {
        $this->setUpdatedAt(new \DateTime('now'));    
        if ($this->getCreatedAt() === null) {
            $this->setCreatedAt(new \DateTime('now'));
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(?string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getCoverImagePath()
    {
        return 'img/'.UploaderHelper::PLACE_IMAGE.'/'.$this->getCoverImage();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Event[]
     */
    public function getEvents(): Collection
    {
        return $this->events;
    }

    public function addEvent(Event $event): self
    {
        if (!$this->events->contains($event)) {
            $this->events[] = $event;
            $event->setPlace($this);
        }

        return $this;
    }

    public function removeEvent(Event $event): self
    {
        if ($this->events->contains($event)) {
            $this->events->removeElement($event);
            // set the owning side to null (unless already changed)
            if ($event->getPlace() === $this) {
                $event->setPlace(null);
            }
        }

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getDistrict(): ?District
    {
        return $this->district;
    }

    public function setDistrict(?District $district): self
    {
        $this->district = $district;

        return $this;
    }

    public function getLatitude()
    {
        return $this->latitude;
    }

    public function setLatitude($latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude()
    {
        return $this->longitude;
    }

    public function setLongitude($longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getPronoun(): ?string
    {
        return $this->pronoun;
    }

    public function setPronoun(?string $pronoun): self
    {
        $this->pronoun = $pronoun;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

templates/place/_collection.html.twig
{% block _place_multiTitles_widget %}
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter-title" value="0">
    <div class="form-group m-0 text-center button-add">
        <button type="button" id="add-title" class="btn btn-secondary btn-block">Ajouter un autre nom au lieu</button>
    </div>
{% endblock %}

{% block _place_multiTitles_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _place_multiTitles_entry_widget %}
    <div class="form-group" id="block_title_{{id}}">
        <div class="row mb-0">
            <div class="col-10 px-0">
                <div class="row m-0">
                    <div class="col px-0">
                        {{ form_widget(form, { 'attr': {'placeholder': "Nom alternatif"} }) }}
                    </div>
                </div>
            </div>
            <div class="col-2 pr-0">
                <button type="button" data-action="delete" data-target="#block_title_{{id}}" class="btn btn-danger btn-block">X</button>
            </div>
        </div>
    </div>
{% endblock %}


{% block _place_links_widget %}
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter-link" value="0">
    <div class="form-group m-0 text-center button-add">
        <button type="button" id="add-link" class="btn btn-secondary btn-block">Ajouter un lien vers un autre site</button>
    </div>
{% endblock %}

{% block _place_links_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _place_links_entry_widget %}
    <div class="form-group" id="block_link_{{id}}">
        <div class="row mb-0">
            <div class="col-10 px-0">
                <div class="row m-0">
                    <div class="col px-0">
                        {{ form_widget(form, { 'attr': {'placeholder': "URL vers un site du lieu"} }) }}
                    </div>
                </div>
            </div>
            <div class="col-2 pr-0">
                <button type="button" data-action="delete" data-target="#block_link_{{id}}" class="btn btn-danger btn-block">X</button>
            </div>
        </div>
    </div>
{% endblock %}


{% block _place_rooms_widget %}
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter-room" value="0">
    <div class="form-group m-0 text-center button-add">
        <button type="button" id="add-room" class="btn btn-secondary btn-block">Ajouter un salle</button>
    </div>
{% endblock %}

{% block _place_rooms_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _place_rooms_entry_widget %}
    <div class="form-group" id="block_room_{{id}}">
        <div class="row mb-0">
            <div class="col-10 px-0">
                <div class="row m-0">
                    <div class="col px-0">
                        {{ form_widget(form.name) }}
                    </div>
                </div>
            </div>
            <div class="col-2 pr-0">
                <button type="button" data-action="delete" data-target="#block_room_{{id}}" class="btn btn-danger btn-block">X</button>
            </div>
        </div>
    </div>
{% endblock %}

{#% block _place_placekinds_widget %}
    <p>Ici, nous voulons ajouter un ou plusieurs types</p>
    
    {{ form_widget(form) }}
        
    <input type="hidden" id="widgets-counter" value="0">
    
    <div class="form-group">
        <button type="button" id="add-placekind" class="btn btn-primary">Ajouter un type</button>
    </div>
{% endblock %}

{% block _place_placekinds_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _place_placekinds_entry_widget %}
    <div class="form-group" id="block_{{id}}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.name) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %#}

templates/place/_map.html.twig
<script type="text/javascript">

  window.onload=function(){
          
    /*Custom marker */
    PlaceMarker = L.CircleMarker.extend({
      options: {
        id: '',
        radius: 5,
        weight: 1,
        opacity: 1,
        fillOpacity: 0.8
      }
    });

    var LeafIcon = L.Icon.extend({
        options: {
            //shadowUrl: '/leaf-shadow.png',
            iconSize:     [12, 20], // size of the icon
            //shadowSize:   [50, 64], // size of the shadow
            //iconAnchor:   [0, 0], // point of the icon which will correspond to marker's location
            //shadowAnchor: [4, 62],  // the same for the shadow
            popupAnchor:  [0, -10] // point from which the popup should open relative to the iconAnchor
        }
    });

    /*Include the marker data and create the layers */
    var data = [
      {% for place in widget.map.markers %}
        {% set countOfEvents = place.countOfEvents %}
        {% set place = place[0] %}
        ["{% if place.placekindPrimary %}{{ place.placekindPrimary.slug }}{% else %}{% endif %}", {{ place.latitude }}, {{ place.longitude }}, "{{ place.title|e('js') }}", "{{ place.number|e('js') }} {{ place.address|e('js') }}, {{ place.city.name|e('js') }}", "{{ countOfEvents }} évènements à venir"],
      {% endfor %}
    ];

    var greenIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/green.png'}),
        blueIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/blue.png'}),
        redIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/red.png'}),
        orangeIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/orange.png'}),
        greyIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/grey.png'}),
        blackIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/black.png'}),
        pinkIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/pink.png'}),
        brownIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/brown.png'}),
        yellowIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/yellow.png'}),
        whiteIcon = new LeafIcon({iconUrl: '/uploads/common/marker/color/white.png'});

    var concert = new L.LayerGroup(),
        soiree = new L.LayerGroup(),
        theatre = new L.LayerGroup(),
        exposition = new L.LayerGroup(),
        cinema = new L.LayerGroup(),
        danse = new L.LayerGroup(),
        musique_classique = new L.LayerGroup(),
        action_citoyenne = new L.LayerGroup(),
        sport = new L.LayerGroup(),
        autre = new L.LayerGroup();

    for (var i = 0; i < data.length; i++) {
      if (data[i][0] == "musee") {var iconColor = blueIcon }
      else if (data[i][0] == "lieu-alternatif") {var iconColor = greenIcon }
      else if (data[i][0] == "centre-socio-culturel") {var iconColor = blackIcon }
      else if (data[i][0] == "salle-polyvalente") {var iconColor = yellowIcon }
      else if (data[i][0] == "bar") {var iconColor = redIcon }
      else if (data[i][0] == "bibliotheque") {var iconColor = orangeIcon }
      else if (data[i][0] == "restaurant") {var iconColor = pinkIcon }
      else if (data[i][0] == "cinema") {var iconColor = brownIcon }
      else if (data[i][0] == "salle-de-spectacle") {var iconColor = greyIcon }
      else {var iconColor = whiteIcon }

      marker = L.marker([data[i][1], data[i][2]], {
        //color: "#000000",
        rubric: data[i][0],
        place: data[i][3],
        address: data[i][4],
        count: data[i][5],
        tags: data[i][6],
        icon: iconColor
      }).bindTooltip(data[i][3],{direction: 'top', offset:[0,-20]}).addTo(concert).bindPopup(data[i][3]).on('click', markerOnClick);
    
    }

    /* Some handy variables*/
     /*var booklayers = [concert, soiree, theatre, exposition, cinema, danse, sport, autre]
   */
    var booklayers = [concert, soiree, theatre, exposition, cinema, musique_classique, action_citoyenne, danse, sport, autre];
    


      /*Initialise map; change zoom control position*/
    var map = L.map('map', {
      layers: booklayers
    }).setView([{{ widget.map.center }}], {{ widget.map.zoom }});
    //map.zoomControl.setPosition('bottomright');

    /*Add tileLayers*/
    mapLink = '<a href="https://openstreetmap.org">OpenStreetMap<\/a>';
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: '&copy; ' + mapLink + ' Contributors',
      maxZoom: 19,
    }).addTo(map);

    /* Open modal & center map on marker click 	*/
    function markerOnClick(e) {
      var rubric = this.options.rubric;
      var place = this.options.place;
      var address = this.options.address;
      var count = this.options.count;
      $(".event-content").html('<div class="event-map"><a class="rubric-map">' + rubric + '</a><h4>' + place + '</h4><div class="block-detail"><div class="button-detail" ><i class="fa fa-map-marker fa-lg"></i> ' + address + '</div><div class="text-center mt-3" ><div class="btn btn-secondary btn-sm" >' + count + '</div></div></div></div>');
      $('#emptymodal').modal('show');
      map.setView(e.target.getLatLng());
      e.preventDefault();
    }

    /*Close modal on map click */
    map.on('click', function(e) {
        $(".event-content").html('');
      $('.modal').modal('hide');
    });


  /*
    L.control.tagFilterButton({
        data: ['omnis', 'facilis', 'jeune public'],
        filterOnEveryClick: true,
        icon: '<i class="fa fa-suitcase"></i>',
    }).addTo(map);

    L.control.tagFilterButton({
        data: ['concert', 'soirée', 'théâtre', 'exposition', 'cinéma', 'musique classique', 'action citoyenne', 'danse', 'sport', 'autre'],
        filterOnEveryClick: true,
        icon: '<i class="fa fa-pagelines"></i>',
    }).addTo(map);

    jQuery('.easy-button-button').click(function() {
      target = jQuery('.easy-button-button').not(this);
      target.parent().find('.tag-filter-tags-container').css({
          'display' : 'none',
      });
    });
  */

  }

</script>

templates/place/_place.html.twig
{% set url = path('place_show',{'slug': place.slug }) %}


    <div class="sortie-bloc item mb-4">

        <div class="block-visual">

            <div class="block-badge">
                {% if place.placekindPrimary %}
                    <a href="{{ path('search_by_placekind',{'slug': place.placekindPrimary.slug }) }}">
                        {{ place.placekindPrimary.name | badge({'color':'danger'}) }}
                    </a> 
                {% endif %}
                {% if place.placekindSecondary %}
                    <a href="{{ path('search_by_placekind',{'slug': place.placekindSecondary.slug }) }}">
                        {{ place.placekindSecondary.name | badge({'color':'danger'}) }}
                    </a> 
                {% endif %}
                {% if place.placekindTertiary %}
                    <a href="{{ path('search_by_placekind',{'slug': place.placekindTertiary.slug }) }}">
                        {{ place.placekindTertiary.name | badge({'color':'danger'}) }}
                    </a> 
                {% endif %}
                {% for placetag in place.placetags %}
                    {{ placetag.name | badge({'color':'primary'}) }}
                {% endfor %}
            </div>

            <div class="block-image">
                <a href="{{ url }}">

                    <div class="img-blur">
                        {% if place.coverImage %}
                            {% if place.coverImage starts with 'http' %}
                                <img src="{{ place.coverImage }}" />
                            {% else %}
                                <img src="{{ asset(place.coverImagePath) }}" />
                                {# <img src="{{ asset(place.coverImagePath)|imagine_filter('resize_thumbnail') }}" /> #}
                            {% endif %}
                        {% else %}
                            <img src="/uploads/common/visuel/autre.jpg" />
                        {% endif %}
                    </div>

                    <div class="img-contain">
                        {% if place.coverImage %}
                            {% if place.coverImage starts with 'http' %}
                                <img src="{{ place.coverImage }}" />
                            {% else %}
                                <img src="{{ asset(place.coverImagePath) }}" />
                                {# <img src="{{ asset(place.coverImage)|imagine_filter('resize_thumbnail') }}" /> #}
                            {% endif %}
                        {% else %}
                            <img src="/uploads/common/visuel/autre.jpg" />
                        {% endif %}
                    </div>

                </a>
                    
                <a href="{{ path('place_like',{'id': place.id}) }}" class="block-favorite js-like">
                    <span class="js-label">Ajouter aux favoris</span>
                    {% if app.user and place.isLikedByUser(app.user) %}
                        <i class="fa fa-star"></i>
                    {% else %} 
                        <i class="fa fa-thumbs-up"></i>
                    {% endif %} 
                    <span class="js-likes">{{ place.likes|length }}</span>
                </a>
            </div>

        </div>
        
        <div class="details">

            {% set week = ["dimanche","lundi","mardi","mercredi","jeudi","vendredi","samedi"] %}
            {% set month = ["décembre","janvier","février","mars","avril","mai","juin","juillet","août","septembre","octobre","novembre","décembre"] %}

            <div class="block-date">
                {% if minDate == "now"|date("Y-m-d") and maxDate == "now"|date("Y-m-d") %}
                    Aujourd'hui le
                    {{ week[minDate|date("w")] }}
                    {{ minDate|date('j') }}
                    {{ month[minDate|date('n')] }}
                    {{ minDate|date('Y') }}
                {% elseif minDate == "now"|date("Y-m-d") %}
                    À partir d'aujourd'hui le
                    {{ week[minDate|date("w")] }}
                    {{ minDate|date('j') }}
                    {{ month[minDate|date('n')] }}
                    {{ minDate|date('Y') }}
                {% elseif maxDate == "now"|date("Y-m-d") %}
                    Aujourd'hui, dernier jour de la programmation
                {% elseif minDate >= "now"|date("Y-m-d") %}
                    Prochaine date le 
                    {{ week[minDate|date("w")] }}
                    {{ minDate|date('j') }}
                    {{ month[minDate|date('n')] }}
                    {{ minDate|date('Y') }}
                {% elseif maxDate >= "now"|date("Y-m-d") %}
                    Programmé jusqu'au
                    {{ week[maxDate|date("w")] }}
                    {{ maxDate|date('j') }}
                    {{ month[maxDate|date('n')] }}
                    {{ maxDate|date('Y') }}
                {% else %}
                    Depuis le     
                    {{ week[minDate|date("w")] }}
                    {{ minDate|date('j') }}
                    {{ month[minDate|date('n')] }}
                    {{ minDate|date('Y') }}
                {% endif %}
            </div>

            <div class="block-title">
                <h5><a href="{{ url }}">{{ place.title }}</a>{% if place.city.name not in place.title %}, <a class="city" href="{{ path('search_by_city',{'slug': place.city.slug }) }}">{{ place.city.name }}</a>{% endif %}</h5>
            </div>
            

            {#% if place.countOfEvents %}
                {{ place.countOfEvents }}
            {% endif %#}

            <h6 class="pt-1">
                {#% if place.events | length > 1 %}
                    {{place.events | length}} évènements à venir
                {% elseif place.events | length > 0 %}
                    {{place.events | length}} évènement à venir
                {% else %}
                    Aucun évènement à venir
                {% endif %#}


                {% if countOfEvents > 1 %}
                    {{ countOfEvents }} évènements {{ title.afterCount.plural }}
                {% elseif countOfEvents == 1 %}
                    {{ countOfEvents }} évènement {{ title.afterCount.one }}
                {% else %}
                    Aucun évènement à venir
                {% endif %}
                
            </h6>

            <div class="info">
                {% if place.district %}
                    {{ place.district.name }}
                 {% endif %}
            </div>

        </div>
{#
        <div class="more-info">
            <a href="{{ url }}" class="btn btn-primary">Plus d'info</a>
        </div>
#}
    </div>

templates/place/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'un lieu{% endblock %}

{% form_theme formPlace 'place/_collection.html.twig' %}

{% block body %}

    <div class="container my-4">
        <h2 class="text-center mb-5"><u>Modification du lieu :</u> <strong>{{place.title}}</strong></h2>

        {{ form_start(formPlace) }}

            {#{ form_widget(form) }#}
            {% include 'place/_form.html.twig' %}

            <button type="submit" class="btn btn-primary btn-block my-5">Enregistrer les modifications</button>

        {{ form_end(formPlace) }}
            
    </div>

{% endblock %}

{#% block stylesheets %}
    <!--<link rel="stylesheet" href="/css/trumbowyg.min.css">-->
{% endblock %#}

{% block javascripts %}
    <!--
    <script src="/js/trumbowyg.min.js"></script>
    <script src="/js/trumbowyg-fr.js"></script>
    <script type="text/javascript">
        $.trumbowyg.svgPath = '/js/icons.svg';
        $('#place_description').trumbowyg({
            lang: 'fr',
            /**/btns: [
                ['viewHTML'],
                ['undo', 'redo'], // Only supported in Blink browsers
                ['formatting'],
                ['strong', 'em', 'del'],
                //['superscript', 'subscript'],
                ['link'],
                //['insertImage'],
                ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['fullscreen']
            ]
        });
    </script>
    -->

    <script src="/js/place.js"></script>
    <script src="/js/image.js"></script>
{% endblock %}