src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Service\UploaderHelper;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Un utilisateur utilise déjà cette adresse email"
 * )  
 */
class User implements  UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer le prénom")
     * @Assert\Length(min=3, max=255, minMessage="Le prénom doit faire plus de 2 caractères !", maxMessage="Le prénom doit faire maximum 255 caractères !")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez indiquer le nom")
     * @Assert\Length(min=3, max=255, minMessage="Le nom de famille doit faire plus de 2 caractères !", maxMessage="Le nom de famille doit faire maximum 255 caractères !")
     */
    private $lastName;

    private $fullName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Email(message="Veuillez indiquer une adresse email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @Assert\Regex(
     * pattern = "/^(?=.*\d)(?!.*(.)\1{2}).*[a-z]/m",
     * match=true,
     * message="Votre mot de passe doit comporter au moins huit caractères, dont une lettre et un chiffre.")
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Vous n'avez pas confirmé correctement votre mot de passe")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=250, maxMessage="Votre intro doit faire maximum 250 caractères !")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $presentation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity=Claim::class, mappedBy="owner", orphanRemoval=true)
     */
    private $claims;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $token;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $passwordRequestedAt;

    /**
     * @ORM\OneToMany(targetEntity=EventLike::class, mappedBy="user", orphanRemoval=true)
     */
    private $eventLikes;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_connection_at;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $level;

    /**
     * @ORM\OneToMany(targetEntity=PlaceLike::class, mappedBy="user", orphanRemoval=true)
     */
    private $placeLikes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebookId;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $googleId;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isVisible;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isActivated;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isChecked;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isVolunteer;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $registrationAt;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $multiIp = [];


    /**
     * @ORM\ManyToMany(targetEntity=Artist::class, inversedBy="editors")
     */
    private $artistEditors;

    /**
     * @ORM\ManyToMany(targetEntity=Organizer::class, inversedBy="editors")
     */
    private $organizerEditors;

    /**
     * @ORM\ManyToMany(targetEntity=Event::class, inversedBy="editors")
     */
    private $eventEditors;

    /**
     * @ORM\ManyToMany(targetEntity=Place::class, inversedBy="editors")
     */
    private $placeEditors;

    /**
     * @ORM\ManyToMany(targetEntity=Festival::class, inversedBy="editors")
     */
    private $festivalEditors;


    /**
     * @ORM\ManyToMany(targetEntity=Artist::class, mappedBy="affirmers")
     */
    private $artistAffirmers;

    /**
     * @ORM\ManyToMany(targetEntity=Organizer::class, mappedBy="affirmers")
     */
    private $organizerAffirmers;

    /**
     * @ORM\ManyToMany(targetEntity=Place::class, mappedBy="affirmers")
     */
    private $placeAffirmers;

    /**
     * @ORM\ManyToMany(targetEntity=Festival::class, mappedBy="affirmers")
     */
    private $festivalAffirmers;



    /**
     * @ORM\OneToMany(targetEntity=Artist::class, mappedBy="author")
     */
    private $artistAuthors;

    /**
     * @ORM\OneToMany(targetEntity=Organizer::class, mappedBy="author")
     */
    private $organizerAuthors;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="author")
     */
    private $eventAuthors;

    /**
     * @ORM\OneToMany(targetEntity=Place::class, mappedBy="author")
     */
    private $placeAuthors;

    /**
     * @ORM\OneToMany(targetEntity=Festival::class, mappedBy="author")
     */
    private $festivalAuthors;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="moderator")
     */
    private $moderateComments;

    /**
     * @ORM\OneToMany(targetEntity=Subdomain::class, mappedBy="manager")
     */
    private $subdomains;

    /**
     * @ORM\ManyToMany(targetEntity=Subdomain::class, mappedBy="volunteers")
     */
    private $supports;

    /**
     * @ORM\OneToMany(targetEntity=Event::class, mappedBy="verifiedBy")
     */
    private $eventsVerified;

    public function __construct()
    {
        $this->userRoles = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->claims = new ArrayCollection();
        $this->eventLikes = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->placeLikes = new ArrayCollection();
        $this->artistEditors = new ArrayCollection();
        $this->organizerEditors = new ArrayCollection();
        $this->eventEditors = new ArrayCollection();
        $this->placeEditors = new ArrayCollection();
        $this->festivalEditors = new ArrayCollection();
        $this->artistAffirmers = new ArrayCollection();
        $this->organizerAffirmers = new ArrayCollection();
        $this->placeAffirmers = new ArrayCollection();
        $this->festivalAffirmers = new ArrayCollection();
        $this->festivalAuthors = new ArrayCollection();
        $this->artistAuthors = new ArrayCollection();
        $this->organiserAuthors = new ArrayCollection();
        $this->organizerAuthors = new ArrayCollection();
        $this->placeAuthors = new ArrayCollection();
        $this->eventAuthor = new ArrayCollection();
        $this->moderateComments = new ArrayCollection();
        $this->subdomains = new ArrayCollection();
        $this->supports = new ArrayCollection();
        $this->eventsVerified = new ArrayCollection();
    }
    
    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    /**
     * Permet d'initialiser la date de création du compte
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
    */
    public function updatedTimestamps(): void
    {   
        if ($this->getRegistrationAt() === null) {
            $this->setRegistrationAt(new \DateTime('now'));
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getAvatarPath()
    {
        return 'img/'.UploaderHelper::USER_IMAGE.'/'.$this->getAvatar();
    }

    public function getPassword(): ?string
    {
        return $this->hash;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Service\Website;
use App\Repository\UserRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserController extends AbstractController
{
    public function __construct(Website $website)
    {
        $this->website = $website->getArray();
    }
    
    /**
     * @Route("/utilisateur/{slug}", name="user_show")
     */
    public function index(User $user)
    {
        return $this->render('user/index.html.twig', [
            'user'      => $user,
            'website'   => $this->website
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page de {{user.fullName}} {% endblock %}

{% block body %}

<div class="container">
    <div class="row align-items-center">
        <div class="col-3 text-center">
            {% if user.avatar %}
                {% if user.avatar starts with 'http' %}
                    <img src="{{ user.avatar }}" class="avatar mb-3" alt="Avatar de {{user.fullName}}" />
                {% else %}
                    <img src="{{ asset(user.avatarPath) }}" class="avatar mb-3" alt="Avatar de {{user.fullName}}" />
                {% endif %}
            {% endif %}
            <br>
            <span class="badge badge-primary">{{user.eventAuthors | length}} annonce{% if user.eventAuthors | length > 1 %}s{% endif %}</span>
        </div>
        <div class="col-9">
            <h1>{{user.fullName}}</h1>
            
            {% if user.organizerAffirmers|length > 0 %}
                
                {% if user.organizerAffirmers|length == 1 %}
                    <h4>Membre de la structure :</h4>
                {% else %} 
                    <h4>Membre des structures :</h4>
                {% endif %} 

                {% for organizer in user.organizerAffirmers %}
                    <a href="{{ path('artist_show', {'slug': organizer.slug}) }}">{{ organizer.name }}</a>
                {% endfor %}

            {% endif %}

            {% if user.artistAffirmers|length > 0 %}

                {% if user.artistAffirmers|length == 1 %}
                    <h4>Associé à l'artiste :</h4>
                {% else %} 
                    <h4>Associé aux artistes</h4>
                {% endif %} 

                {% for artist in user.artistAffirmers %}
                    <a href="{{ path('artist_show', {'slug': artist.slug}) }}">{{ artist.name }}</a>
                    {#{ dump(artist) }#}
                {% endfor %}

            {% endif %}
            
            {% if user is same as(app.user) %}
                <div class="mt-3">
                    <a href="{{ path('account_profile') }}" class="btn btn-primary mr-2 mb-2">
                        Modifier mes informations
                    </a>
                    <a href="{{ path('account_password') }}" class="btn btn-primary mb-2">
                        Modifier mon mot de passe
                    </a>
                </div>
            {% endif %}



           
        </div>
    </div>

    {{user.presentation | raw}}

    {% if user.eventAuthors | length > 0 %}
        <div class="container">
            <div class="title">
                <h2>Les évènements annoncés par {{user.fullName}}</h2>
                <div class="buttons">
                    <button class="list-view on"><i class="fa fa-bars"></i></button>
                    <button class="grid-view"><i class="fa fa-th"></i></button>
                </div>
            </div>
            <div class="wrapper list">
                {% for event in user.eventAuthors %}
                    {% include 'event/_event.html.twig'%}
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="alert alert-warning">
            <p>
                <strong>{{user.fullName}}</strong> n'a pas encore annoncé d'évènement sur le site !
            </p>
        </div>
    {% endif %}

</div>

{% endblock %}